before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: JCXAhPn8Cfw7goBAjKEszrJybmfQ3GkYztkxvh5MC2FRgsvKELRdj2BUn7pUOHAvcLkOXclbsu7Ieq5uTwfob/M15cCOtf50NVvHQ/6Ugn8pp/m54XFY6vOI4+exlfJZtH5CgwmQePpPHjYS4mvZiRigdwH16JLul9xyh26f97ID+1SxXlq4+YePi7zUrvl6KlxaEecx6KX/zo/9I+fJUNeKKlAuBmzFO1OGrmjQXswxUZwNwXmyzpPeSvXn8eg8R/mRpLYQZKGm48vsUvYo35VzogGDP2aGNTobfcrwOhjG/z16MqHbQm+B/d64KM2d0FEY+xm5Kc7E/hqJlRBlf+WtKWtmZQxDb/d/PDrSSVhbAmTQP+KCnmqjE58Ul2HLl5Y0Gxgx8l12t2IR2YD9+e4gpt/zUfEH5MXYZb0MOSRnpngBrm+v7Houcutq6o5C8Q7Prhx8PS2kWIDCsd/7nslX/BvF0hrTIciDA9DzRB2ZzBr0HI2s18jGQfz6gnkZK+MjUw6w0mDJ8vNL5Y/qVt8UWjgQxgmUpqAQmeBVVX2+W+TXS5baMCopXVkV2/LQYW0PFEMBbp/iI9/FvSlZb3fOFc8HeIPOQd7tY+o5jT+ukCfyYFGUw1e+35rvhRMYQhrJjHV+tp+Ja4+s1c7wOw/6vfpGb8hsCa1gfzCK4Uo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
